version: '3'
services: 
        psdb:
                container_name: psdb
                restart: always
                image: postgres:13.4-alpine
                environment:
                        POSTGRES_USER: ${DB_USER}
                        POSTGRES_PASSWORD: ${DB_PASS}
                        POSTGRES_DB: ${DB_NAME}
        kanban:
                container_name: kanban
                restart: always
                build: .
                ports:
                        - ${APP_PORT}:${APP_PORT}
                links:
                        - psdb
